#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

global
    log     /dev/log local0
    maxconn 2048
    user    haproxy
    group   haproxy
    tune.ssl.default-dh-param 2048


defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
    option  forwardfor
    option  http-server-close

listen 41185-lb-01
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 41185-web-02 54.237.58.228:80 check
        server 41185-web-01 54.89.53.150:80 check

listen appname 0.0.0.0:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 41185-web-02 54.237.58.228:80 check
        server 41185-web-01 54.89.53.150:80 check
frontend www-http
    bind *:80
    http-request add-header X-Served-By http
    default_backend www-backend

frontend www-https
    bind *:443 ssl crt /etc/ssl/certs/www.twinner.tech.pem
    http-request add-header X-Served-By https
    default_backend web-servers

backend web-servers
    balance  roundrobin
    redirect scheme https if !{ ssl_fc }
    server 41185-web-01 54.89.53.150:80 check
    server 41185-web-02 54.237.58.228:80 check
    option httpchk
