#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read username password uid gid info home shell; do
  echo "The user $USERNAME is part of the $GROUP_ID gang,"\
  "lives in $HOME_DIRECTORY and rides $(COMMAND/SHELL)."\
  "$(USER ID\'s) place is protected by the passcode $PASSWORD,"\
  "more info about the user here: $(USER ID INFO)"
done < "/etc/passwd"
